import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// One source of truth for the policy: injected into the built HTML as a meta tag (so it travels with
// the files on any static host) and emitted as a real `_headers` file for Cloudflare Pages.
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  'font-src https://fonts.gstatic.com',
  "img-src 'self' data: https://upload.wikimedia.org",
  "connect-src 'self' https://en.wikipedia.org https://api.open-meteo.com",
  "base-uri 'self'",
  "form-action 'none'",
  "object-src 'none'",
].join('; ')

// Header-only directives: browsers ignore these in a meta tag and log a warning, so they go to `_headers` alone.
const CSP_HEADER = `${CSP}; frame-ancestors 'none'`

const HEADERS = `# Generated by vite.config.ts. Cloudflare Pages reads this file; other hosts fall back to the meta tag.
/*
  Content-Security-Policy: ${CSP_HEADER}
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: geolocation=(self), camera=(), microphone=()

# Hashed filenames: safe to keep forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# Not content-hashed, but it changes only when the land data is regenerated.
/globe-dots.bin
  Cache-Control: public, max-age=86400
`

// base is '/' by default, which is what Cloudflare Pages and a custom domain want.
// Set VITE_BASE (e.g. "/truechiller/") only when serving from a sub-path, such as GitHub Pages.
export default defineConfig(({ command }) => ({
  plugins: [
    react(),
    {
      name: 'truechiller-security-headers',
      // The dev server needs inline scripts for React Fast Refresh, so the policy is production-only.
      transformIndexHtml: (html: string) =>
        command === 'build'
          ? html.replace('<meta charset="UTF-8" />', `<meta charset="UTF-8" />\n    <meta http-equiv="Content-Security-Policy" content="${CSP}" />`)
          : html,
      generateBundle() {
        this.emitFile({ type: 'asset', fileName: '_headers', source: HEADERS })
      },
    },
  ],
  base: process.env.VITE_BASE ?? '/',
  build: {
    target: 'es2022',
    sourcemap: false,
    chunkSizeWarningLimit: 1200,
    rollupOptions: {
      output: {
        manualChunks: (id: string) => (id.includes('node_modules/three') ? 'three' : undefined),
      },
    },
  },
}))
